#!/command/with-contenv bash

set -eu
set -o pipefail

if [[ "${PROTOCOL,,}" != "wayland" ]]; then
    exec sleep infinity
fi

if [[ "${TORCHPOD_MODE,,}" == *"vnc"* ]]; then
    echo "GEMFIELD: USE VNC. start krfb..."
    s6-svwait /run/service/kde
    exec s6-setuidgid $TORCHPOD_USER /usr/bin/krfb --nodialog
elif [[ "${TORCHPOD_MODE,,}" == "rdp" ]]; then
    exec sleep infinity
elif [[ "${TORCHPOD_MODE,,}" == "local" ]]; then
    exec sleep infinityq
else
    echo "GEMFIELD ERROR: do not support ${TORCHPOD_MODE} mode. pick one from VNC,RDP,VNCRDP."
    exit 1
fi
