#!/command/with-contenv bash

set -eu
set -o pipefail

if [[ "${PROTOCOL,,}" != "x11" ]]; then
    exec sleep infinity
fi

if [[ "${TORCHPOD_MODE,,}" == "vnc" ]]; then
    exec sleep infinity
elif [[ "${TORCHPOD_MODE,,}" == *"rdp"* ]]; then
    echo "GEMFIELD: USE RDP. start xrdp..."
    s6-svwait /run/service/kde
    exec /usr/sbin/xrdp -nodaemon
elif [[ "${TORCHPOD_MODE,,}" == "local" ]]; then
    exec sleep infinity
else
    echo "GEMFIELD ERROR: do not support ${TORCHPOD_MODE} mode. pick one from VNC,RDP,VNCRDP."
    exit 1
fi


