#!/command/with-contenv bash

set -eu
set -o pipefail

if [[ "${PROTOCOL,,}" != "x11" ]]; then
    exec sleep infinity
fi

if [[ "${TORCHPOD_MODE,,}" == *"vnc"* ]]; then
    echo "GEMFIELD: USE VNC. start vncconfig..."
    s6-svwait /run/service/tigervnc
    exec s6-setuidgid $TORCHPOD_USER vncconfig -nowin
elif [[ "${TORCHPOD_MODE,,}" == "rdp" ]]; then
    exec sleep infinity
elif [[ "${TORCHPOD_MODE,,}" == "local" ]]; then
    exec sleep infinity
else
    echo "GEMFIELD ERROR: do not support ${TORCHPOD_MODE} mode. pick one from VNC,RDP,VNCRDP."
    exit 1
fi


