#!/command/with-contenv bash

set -eu
set -o pipefail

if [[ "${PROTOCOL,,}" != "x11" ]]; then
    exec sleep infinity
fi

if [[ "${TORCHPOD_MODE,,}" == *"vnc"* ]]; then
    echo "GEMFIELD: USE VNC. start Xvnc..."
    exec s6-setuidgid $TORCHPOD_USER /usr/bin/Xvnc "$DISPLAY" -geometry "$SCR_WIDTH"x"$SCR_HEIGHT" -depth 16 -SecurityTypes none -AlwaysShared
elif [[ "${TORCHPOD_MODE,,}" == "rdp" ]]; then
    exec sleep infinity
elif [[ "${TORCHPOD_MODE,,}" == "local" ]]; then
    exec sleep infinity
else
    echo "GEMFIELD ERROR: do not support ${TORCHPOD_MODE} mode. pick one from VNC,RDP,VNCRDP."
    exit 1
fi
