#!/command/with-contenv bash

set -eu
set -o pipefail

if [[ "${TORCHPOD_MODE,,}" == *"vnc"* ]]; then
    echo "GEMFIELD: USE VNC. start nginx..."
    s6-svwait /run/service/novnc
    exec /usr/sbin/nginx
elif [[ "${TORCHPOD_MODE,,}" == "rdp" ]]; then
    exec sleep infinity
elif [[ "${TORCHPOD_MODE,,}" == "local" ]]; then
    exec sleep infinity
else
    echo "GEMFIELD ERROR: do not support ${TORCHPOD_MODE} mode. pick one from VNC,RDP,VNCRDP."
    exit 1
fi


